name: MySQL

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: baijunyao
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: MySQL 8.0
        run: |
          docker build -f mysql/8.0/Dockerfile -t baijunyao/mysql:8.0 mysql/8.0/
          docker push baijunyao/mysql:8.0
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v3.0.0
        if: always()
        with:
          slack_channel_id: CMRA2NF3L
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
