name: NGINX

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: azure/docker-login@v1
        with:
          username: baijunyao
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: NGINX 1.7
        run: |
          docker build -f nginx/1.7/Dockerfile -t baijunyao/nginx:1.7 nginx/1.7/
          docker push baijunyao/nginx:1.7
      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v2.0.0
        if: always()
        with:
          channel: CMRA2NF3L
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
          job_context: ${{ toJson(job) }}
