name: PHP

on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: azure/docker-login@v1
        with:
          username: baijunyao
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: PHP 7.2 base
        run: |
          docker build -f php/7.2/Dockerfile -t baijunyao/php:7.2 php/7.2/
          docker push baijunyao/php:7.2

      - name: PHP 7.2 local
        run: |
          docker build -f php/7.2/Dockerfile.local -t baijunyao/php:7.2-local php/7.2/
          docker push baijunyao/php:7.2-local

      - name: PHP 7.2 production
        run: |
          docker build -f php/7.2/Dockerfile.production -t baijunyao/php:7.2-production php/7.2/
          docker push baijunyao/php:7.2-production

      - name: PHP 7.3 base
        run: |
          docker build -f php/7.3/Dockerfile -t baijunyao/php:7.3 php/7.3/
          docker push baijunyao/php:7.3

      - name: PHP 7.3 local
        run: |
          docker build -f php/7.3/Dockerfile.local -t baijunyao/php:7.3-local php/7.3/
          docker push baijunyao/php:7.3-local

      - name: PHP 7.3 production
        run: |
          docker build -f php/7.3/Dockerfile.production -t baijunyao/php:7.3-production php/7.3/
          docker push baijunyao/php:7.3-production

      - name: PHP 7.4 base
        run: |
          docker build -f php/7.4/Dockerfile -t baijunyao/php:7.4 php/7.4/
          docker push baijunyao/php:7.4

      - name: PHP 7.4 local
        run: |
          docker build -f php/7.4/Dockerfile.local -t baijunyao/php:7.4-local php/7.4/
          docker push baijunyao/php:7.4-local

      - name: PHP 7.4 production
        run: |
          docker build -f php/7.4/Dockerfile.production -t baijunyao/php:7.4-production php/7.4/
          docker push baijunyao/php:7.4-production

      - name: Slack Notify
        uses: baijunyao/action-slack-notify@v2.2.0
        if: always()
        with:
          channel: CMRA2NF3L
          slack_bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
          github_context: ${{ toJson(github) }}
          job_context: ${{ toJson(job) }}
